/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TrustLogo = {
  _id: string;
  _type: "trustLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order: number;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order: number;
  question: string;
  answer?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order: number;
  quote: string;
  name?: string;
  company?: string;
};

export type WorkItem = {
  _id: string;
  _type: "workItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order: number;
  name: string;
  meta?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order: number;
  title: string;
  description?: string;
  bullets?: Array<string>;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  blurb?: string;
  email?: string;
  phone?: string;
  social?: Array<{
    label?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type Cta = {
  _id: string;
  _type: "cta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  body?: string;
  email?: string;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  statement: string;
  tags?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  badge?: string;
  heading: string;
  tagline?: string;
  body?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  trustLabel?: string;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | TrustLogo
  | SanityImageCrop
  | SanityImageHotspot
  | Faq
  | Testimonial
  | WorkItem
  | Service
  | Footer
  | Cta
  | About
  | Hero
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{ trustLabel, seo }
export type SiteSettingsQueryResult = {
  trustLabel: string | null;
  seo: {
    metaTitle?: string;
    metaDescription?: string;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: heroQuery
// Query: *[_type == "hero"][0]{ badge, heading, tagline, body }
export type HeroQueryResult = {
  badge: string | null;
  heading: string;
  tagline: string | null;
  body: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: aboutQuery
// Query: *[_type == "about"][0]{ eyebrow, statement, tags, image }
export type AboutQueryResult = {
  eyebrow: string | null;
  statement: string;
  tags: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ctaQuery
// Query: *[_type == "cta"][0]{ heading, body, email }
export type CtaQueryResult = {
  heading: string;
  body: string | null;
  email: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: footerQuery
// Query: *[_type == "footer"][0]{ name, blurb, email, phone, social }
export type FooterQueryResult = {
  name: string | null;
  blurb: string | null;
  email: string | null;
  phone: string | null;
  social: Array<{
    label?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: servicesQuery
// Query: *[_type == "service"] | order(order asc){ title, description, bullets }
export type ServicesQueryResult = Array<{
  title: string;
  description: string | null;
  bullets: Array<string> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: workItemsQuery
// Query: *[_type == "workItem"] | order(order asc){ name, meta, image, url, "imageDimensions": image.asset->metadata.dimensions{width, height} }
export type WorkItemsQueryResult = Array<{
  name: string;
  meta: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  url: string | null;
  imageDimensions: {
    width: number;
    height: number;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial"] | order(order asc){ quote, name, company }
export type TestimonialsQueryResult = Array<{
  quote: string;
  name: string | null;
  company: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: faqsQuery
// Query: *[_type == "faq"] | order(order asc){ question, answer }
export type FaqsQueryResult = Array<{
  question: string;
  answer: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: trustLogosQuery
// Query: *[_type == "trustLogo"] | order(order asc){ name, logo, "logoDimensions": logo.asset->metadata.dimensions{width, height} }
export type TrustLogosQueryResult = Array<{
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoDimensions: {
    width: number;
    height: number;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{ trustLabel, seo }': SiteSettingsQueryResult;
    '*[_type == "hero"][0]{ badge, heading, tagline, body }': HeroQueryResult;
    '*[_type == "about"][0]{ eyebrow, statement, tags, image }': AboutQueryResult;
    '*[_type == "cta"][0]{ heading, body, email }': CtaQueryResult;
    '*[_type == "footer"][0]{ name, blurb, email, phone, social }': FooterQueryResult;
    '*[_type == "service"] | order(order asc){ title, description, bullets }': ServicesQueryResult;
    '*[_type == "workItem"] | order(order asc){ name, meta, image, url, "imageDimensions": image.asset->metadata.dimensions{width, height} }': WorkItemsQueryResult;
    '*[_type == "testimonial"] | order(order asc){ quote, name, company }': TestimonialsQueryResult;
    '*[_type == "faq"] | order(order asc){ question, answer }': FaqsQueryResult;
    '*[_type == "trustLogo"] | order(order asc){ name, logo, "logoDimensions": logo.asset->metadata.dimensions{width, height} }': TrustLogosQueryResult;
  }
}
