/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  question?: string;
  answer?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type WorkItem = {
  _id: string;
  _type: "workItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  name?: string;
  meta?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  slug?: Slug;
  tagline?: string;
  industry?: string;
  projectType?: string;
  services?: Array<string>;
  client?: string;
  challenge?: string;
  solution?: string;
  showcase?: Array<
    | {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        caption?: string;
        _type: "showcaseBrowser";
        _key: string;
      }
    | {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        caption?: string;
        _type: "showcaseFullWidth";
        _key: string;
      }
    | {
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
        caption?: string;
        _type: "showcaseMobile";
        _key: string;
      }
    | {
        first?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        second?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        caption?: string;
        _type: "showcasePair";
        _key: string;
      }
    | {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        heading?: string;
        text?: string;
        _type: "showcaseDetail";
        _key: string;
      }
  >;
  features?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  technologies?: Array<{
    name?: string;
    reason?: string;
    _key: string;
  }>;
  results?: Array<{
    figure?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  testimonial?: TestimonialReference;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  quote?: string;
  name?: string;
  company?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  description?: string;
  bullets?: Array<string>;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  blurb?: string;
  email?: string;
  phone?: string;
  social?: Array<{
    label?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type Cta = {
  _id: string;
  _type: "cta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  body?: string;
  email?: string;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  statement?: string;
  tags?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  badge?: string;
  heading?: string;
  tagline?: string;
  body?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Faq
  | SanityImageAssetReference
  | TestimonialReference
  | WorkItem
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Service
  | Footer
  | Cta
  | About
  | Hero
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{ seo }
export type SiteSettingsQueryResult = {
  seo: {
    metaTitle?: string;
    metaDescription?: string;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: heroQuery
// Query: *[_type == "hero"][0]{ badge, heading, tagline, body }
export type HeroQueryResult = {
  badge: string | null;
  heading: string | null;
  tagline: string | null;
  body: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: aboutQuery
// Query: *[_type == "about"][0]{ eyebrow, statement, tags, image }
export type AboutQueryResult = {
  eyebrow: string | null;
  statement: string | null;
  tags: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ctaQuery
// Query: *[_type == "cta"][0]{ heading, body, email }
export type CtaQueryResult = {
  heading: string | null;
  body: string | null;
  email: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: footerQuery
// Query: *[_type == "footer"][0]{ name, blurb, email, phone, social }
export type FooterQueryResult = {
  name: string | null;
  blurb: string | null;
  email: string | null;
  phone: string | null;
  social: Array<{
    label?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: servicesQuery
// Query: *[_type == "service"] | order(order asc){ title, description, bullets }
export type ServicesQueryResult = Array<{
  title: string | null;
  description: string | null;
  bullets: Array<string> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: workItemsQuery
// Query: *[_type == "workItem"] | order(order asc){ name, meta, image, url, "slug": slug.current, "imageDimensions": image.asset->metadata.dimensions{width, height} }
export type WorkItemsQueryResult = Array<{
  name: string | null;
  meta: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  url: string | null;
  slug: string | null;
  imageDimensions: {
    width: number | null;
    height: number | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: caseStudySlugsQuery
// Query: *[_type == "workItem" && defined(slug.current)]{ "slug": slug.current, _updatedAt }
export type CaseStudySlugsQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: caseStudyQuery
// Query: *[_type == "workItem" && slug.current == $slug][0]{    name,    url,    tagline,    industry,    projectType,    services,    client,    challenge,    solution,    image,    "imageDimensions": image.asset->metadata.dimensions{width, height},    showcase[]{      _key,      _type,      caption,      heading,      text,      image{ ..., "dimensions": asset->metadata.dimensions{width, height} },      first{ ..., "dimensions": asset->metadata.dimensions{width, height} },      second{ ..., "dimensions": asset->metadata.dimensions{width, height} },      images[]{ ..., "dimensions": asset->metadata.dimensions{width, height} }    },    features[]{ _key, title, description },    technologies[]{ _key, name, reason },    results[]{ _key, figure, title, description },    testimonial->{ quote, name, company },    "next": coalesce(      *[_type == "workItem" && defined(slug.current) && order > ^.order] | order(order asc)[0],      *[_type == "workItem" && defined(slug.current) && _id != ^._id] | order(order asc)[0]    ){ name, meta, "slug": slug.current }  }
export type CaseStudyQueryResult = {
  name: string | null;
  url: string | null;
  tagline: string | null;
  industry: string | null;
  projectType: string | null;
  services: Array<string> | null;
  client: string | null;
  challenge: string | null;
  solution: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageDimensions: {
    width: number | null;
    height: number | null;
  } | null;
  showcase: Array<
    | {
        _key: string;
        _type: "showcaseBrowser";
        caption: string | null;
        heading: null;
        text: null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
        first: null;
        second: null;
        images: null;
      }
    | {
        _key: string;
        _type: "showcaseDetail";
        caption: null;
        heading: string | null;
        text: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
        first: null;
        second: null;
        images: null;
      }
    | {
        _key: string;
        _type: "showcaseFullWidth";
        caption: string | null;
        heading: null;
        text: null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
        first: null;
        second: null;
        images: null;
      }
    | {
        _key: string;
        _type: "showcaseMobile";
        caption: string | null;
        heading: null;
        text: null;
        image: null;
        first: null;
        second: null;
        images: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "showcasePair";
        caption: string | null;
        heading: null;
        text: null;
        image: null;
        first: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
        second: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
        images: null;
      }
  > | null;
  features: Array<{
    _key: string;
    title: string | null;
    description: string | null;
  }> | null;
  technologies: Array<{
    _key: string;
    name: string | null;
    reason: string | null;
  }> | null;
  results: Array<{
    _key: string;
    figure: string | null;
    title: string | null;
    description: string | null;
  }> | null;
  testimonial: {
    quote: string | null;
    name: string | null;
    company: string | null;
  } | null;
  next: {
    name: string | null;
    meta: string | null;
    slug: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial"] | order(order asc){ quote, name, company }
export type TestimonialsQueryResult = Array<{
  quote: string | null;
  name: string | null;
  company: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: faqsQuery
// Query: *[_type == "faq"] | order(order asc){ question, answer }
export type FaqsQueryResult = Array<{
  question: string | null;
  answer: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{ seo }': SiteSettingsQueryResult;
    '*[_type == "hero"][0]{ badge, heading, tagline, body }': HeroQueryResult;
    '*[_type == "about"][0]{ eyebrow, statement, tags, image }': AboutQueryResult;
    '*[_type == "cta"][0]{ heading, body, email }': CtaQueryResult;
    '*[_type == "footer"][0]{ name, blurb, email, phone, social }': FooterQueryResult;
    '*[_type == "service"] | order(order asc){ title, description, bullets }': ServicesQueryResult;
    '*[_type == "workItem"] | order(order asc){ name, meta, image, url, "slug": slug.current, "imageDimensions": image.asset->metadata.dimensions{width, height} }': WorkItemsQueryResult;
    '*[_type == "workItem" && defined(slug.current)]{ "slug": slug.current, _updatedAt }': CaseStudySlugsQueryResult;
    '*[_type == "workItem" && slug.current == $slug][0]{\n    name,\n    url,\n    tagline,\n    industry,\n    projectType,\n    services,\n    client,\n    challenge,\n    solution,\n    image,\n    "imageDimensions": image.asset->metadata.dimensions{width, height},\n    showcase[]{\n      _key,\n      _type,\n      caption,\n      heading,\n      text,\n      image{ ..., "dimensions": asset->metadata.dimensions{width, height} },\n      first{ ..., "dimensions": asset->metadata.dimensions{width, height} },\n      second{ ..., "dimensions": asset->metadata.dimensions{width, height} },\n      images[]{ ..., "dimensions": asset->metadata.dimensions{width, height} }\n    },\n    features[]{ _key, title, description },\n    technologies[]{ _key, name, reason },\n    results[]{ _key, figure, title, description },\n    testimonial->{ quote, name, company },\n    "next": coalesce(\n      *[_type == "workItem" && defined(slug.current) && order > ^.order] | order(order asc)[0],\n      *[_type == "workItem" && defined(slug.current) && _id != ^._id] | order(order asc)[0]\n    ){ name, meta, "slug": slug.current }\n  }': CaseStudyQueryResult;
    '*[_type == "testimonial"] | order(order asc){ quote, name, company }': TestimonialsQueryResult;
    '*[_type == "faq"] | order(order asc){ question, answer }': FaqsQueryResult;
  }
}
